"""Pre-build script to gzip web assets and emit PROGMEM bundles."""

import gzip
import hashlib
from pathlib import Path

try:
    from SCons.Script import Import  # type: ignore
except ModuleNotFoundError:
    class _DummyEnv:
        def subst(self, _: str) -> str:
            return str(Path(__file__).resolve().parents[1])

    env = _DummyEnv()
else:
    Import("env")


def _to_c_array(data: bytes, indent: str = "  ") -> str:
    chunks = []
    for offset in range(0, len(data), 16):
        segment = data[offset : offset + 16]
        chunk = ", ".join(f"0x{byte:02x}" for byte in segment)
        chunks.append(f"{indent}{chunk},")
    if chunks:
        chunks[-1] = chunks[-1].rstrip(",")
    return "\n".join(chunks)


def build_bundle() -> None:
    project_dir = Path(env.subst("$PROJECT_DIR"))
    web_dir = project_dir / "web"
    output_header = project_dir / "src" / "web_bundle.h"

    if not web_dir.exists():
        raise SystemExit("Missing 'web' directory with UI assets")

    index_path = web_dir / "index.html"
    if not index_path.exists():
        raise SystemExit("Missing web/index.html")

    raw_bytes = index_path.read_bytes()
    compressed = gzip.compress(raw_bytes, compresslevel=9, mtime=0)
    sha1 = hashlib.sha1(compressed).hexdigest()

    array_body = _to_c_array(compressed)
    header_contents = f"""// Auto-generated by scripts/build_web_bundle.py -- do not edit manually.
#pragma once

#include <Arduino.h>

constexpr const uint8_t INDEX_HTML_GZ[] PROGMEM = {{
{array_body}
}};
constexpr const size_t INDEX_HTML_GZ_LEN = sizeof(INDEX_HTML_GZ);
constexpr const char INDEX_HTML_SHA1[] PROGMEM = "{sha1}";
"""

    output_header.write_text(header_contents + "\n")


build_bundle()
